language: php

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - COMPOSER_ARGS="--no-interaction"

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env:
              - DEPS=lowest
        - php: 7.1
          env:
              - DEPS=latest
        - php: 7.2
          env:
              - DEPS=lowest
        - php: 7.2
          env:
              - DEPS=latest
        - php: 7.3
          env:
              - DEPS=lowest
        - php: 7.3
          env:
              - DEPS=latest
        - php: 7.4
          env:
              - DEPS=lowest
        - php: 7.4
          env:
              - DEPS=latest

addons:
    apt:
        packages:
            - libxml2-utils

before_install:
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install $COMPOSER_ARGS
    - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
    - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
    - stty cols 120 && composer show

script:
    - xmllint --noout --schema vendor/squizlabs/php_codesniffer/phpcs.xsd src/CodingStandard/ruleset.xml
    - composer check

notifications:
    email: false